### ISSUE TITLE
HELTEC 2.90" V2 - Multiple incompatible versions circulating

### ISSUE THREAD

**Issue by todd-herbert** [todd-herbert/heltec-eink-modules#1]
It has come to my attention that "not all displays are created equal". A new batch of 2.90" Black and White displays appears to have a different panel which is not currently supported by this library. This will be investigated in the near future.

**Comment by todd-herbert** [comment]
Preliminary support for the new panel has been added in ce931b6c1bd68e7551cde5f1f1f169fcbb8e0df1
Expect partial refresh support, examples and documentation to follow shortly.

**Comment by todd-herbert** [comment]
Further investigation has revealed that while this new panel does support partial refresh, it is not possible to implement this with paging.

**Comment by timstrasser** [comment]
> Further investigation has revealed that while this new panel does support partial refresh, it is not possible to implement this with paging.

Might this exact issue also cause problems with the 152x152 1.54" displays?

**Comment by todd-herbert** [comment]
> Further investigation has revealed that while this new panel does support partial refresh, it is not possible to implement this with paging.

I was mistaken here. I had misunderstood how partial refresh should be performed for this display.
*The model is **HTE029A1**. Support has been added in the [dev branch](/todd-herbert/heltec-eink-modules/tree/dev), and will be incorporated in a future release.

**Comment by todd-herbert** [comment]
Display supported as of [v2.1.0](/todd-herbert/heltec-eink-modules/releases/tag/v2.1.0)
